API building in progress
psymoney/stocker pull request #11
Opened 2021-02-19 14:50 UTC by psymoney

2021-02-19 17:02 UTC, Jeldo requested changes
코멘트 수정하면 PR수정하기 눌러서 타겟 브랜치를 main이 아닌 dev로 설정한뒤 머지하면 됩니다
앞으로의 브랜치도 main이 아닌 dev 브랜치로 타겟 잡으면 됨미다

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/views.py
>  # TODO(SY): remove index & error view after implementing financials API
필요없는 주석은 삭제해주세요

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +from .views import *
views에서 views를 import하고 있습니당
불필요한 import는 삭제해주세여

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        # get_financial_reports(financials)
불필요한 코멘트 삭제
당장 사용하지 않는 코드는 삭제하는게 맞고,
만약 다음 커밋에 사용할 코드지만 특별한 이유로 코멘트로 남긴다면
// TODO(이름): uncomment when ~~
이런식으로 해당 코멘트의 상단에 넣어주면 좋을듯

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        CompView.set_fsDiv(cons)
아래와 같은 방식으로 get_financials를 정의하게되면 instance method를 정의해놓고 클래스를 통해 접근하는 방식이 됨
사용 자체는 가능한데 이런 경우에는
1. 해당 모듈에서 정의(제일 바깥에서)
2. 파이썬의 함수 내 함수 정의가 되는 특성을 이용해서 get_financials가 사용되는 post내에서 정의
..중에서 사용하는게 더 낫지 않나 싶음.
get_financials가 여러군데에서 사용되는게 아니고 post에서만 사용이 된다면 함수내 정의하는 것이 괜찮을 것 같음

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        corpCode = CompView.get_corpCode(name)
여기도 위와 같고 파이썬에서는 변수 이름을 snakeCase로 하지 않고 lower case를 사용하고 under bar `_` 를 사용해서 최대한 descriptive하게 쓰는게 컨벤션.
https://google.github.io/styleguide/pyguide.html
3.16.에 명명이 필요할 때 참고할만한 네이밍 컨벤션이 있음
i.e., `corpCode` -> `corporation_code`

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        financials = CompView.get_financials(corpCode, CompView.fsDiv)
이것도 `financials`보단 이 데이터를 좀 더 잘 나타낼 수 있는 네이밍을 하면 좋을듯

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +    def get_financials(corpCode, fsDiv):
parameter 네이밍도 같은 이슈

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +            str(reportCode) + "&fs_div=" + fsDiv
여기도

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        fData = urllib.request.Request(URI + encText)
fData도

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        #corpList = request.data()
코드를 주석으로 두기보다는 TODO 코멘트로

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/urls.py
> +from .views import *
중복된 코드

2021-02-19 17:02 UTC, Jeldo commented on Backend/apps/financials/urls.py
> +from rest_framework.request import Request
사용하지 않는 코드 삭제

2021-02-20 07:36 UTC, psymoney commented on Backend/apps/financials/views.py
> +        CompView.set_fsDiv(cons)
좋은 코멘트입니다 함수 내에서 재정의해서 사용하겠음.

2021-02-20 08:41 UTC, Jeldo requested changes

2021-02-20 08:41 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        reportCode = 11011
API키는 공개되면 안되는 값이니까 config파일을 만들어서 import해오는 방식이 좋음
.json 이나 .cnf 등등 여러 방법들이 있는데 이건 나중에 찾아서 해보면 되고..

crtfcKey -> API_Key
bsnsYear -> business_year
reportCode -> report_code

2021-02-20 08:41 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        set_fsDiv(cons)
삭제

2021-02-20 08:41 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        cons = request.query_params["cons"]
consolidation

2021-02-20 08:41 UTC, Jeldo commented on Backend/apps/financials/views.py
> +    def get_corporation_code(name):
class에 정의하는 것이 아니라 post나 module단위(class 바깥)에서 사용하도록 정의

2021-02-20 09:35 UTC, Jeldo requested changes

2021-02-20 09:35 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        corporateName = request.query_params["corporateName"]
python variable `corporateName`은 파이썬에서 사용하는 변수 이름이므로 `corporate_name`, param의 key로 사용되는 string `"corporateName"`은 그대로 사용

2021-02-20 09:35 UTC, Jeldo commented on Backend/apps/financials/views.py
> +            consolidationKey = "OFS"
여기도 같이 수정

2021-02-20 09:46 UTC, Jeldo approved these changes

2021-02-20 09:46 UTC, Jeldo commented
LGTM

2021-02-20 09:48 UTC, merged