Issue#18 add corporation table
psymoney/stocker pull request #19
Opened 2021-02-24 07:26 UTC by psymoney

#18 
기존 DB 쿼리에 반영된 json파일이 반쪽짜리 파일이라 json 파일 업데이트했고 동시에 ticker 없는 비상장 기업들 제외하게 변경했음

2021-02-24 13:59 UTC, Jeldo requested changes

2021-02-24 13:59 UTC, Jeldo commented on Backend/apps/financials/views.py
> +            if len(key) == 6:
built-in function 사용하면 쉽게 체크할 수 있을 듯
https://docs.python.org/3/library/stdtypes.html
str.isdigit() 으로 문자열이 숫자로만 이루어져있는지 확인 가능
```
if key.isdigit():
    return search_by_ticker()
return search_by_name()
```
이런 방식이면 쉽게 될 듯.
다른 언어도 그렇지만 특히 파이썬은 생각보다 굉장히 강력한 built-in function이 많아서 본인이 생각한 기능이 있는지 검색해보면 좋을거임

2021-02-24 13:59 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        def get_corporate_code(key):
두 내부 함수에서 예외처리가 되고 있지 않음
예상 가능한 에러들에 대해서 적절하게 핸들링하고 예측 불가능한 에러는 InternalServer로 반환할 수 있도록 하는 코드가 필요함

문법에서 except까지 보았다면 그럼 예외 처리는 어떻게 하는지 찾아봐야 할텐데
`python error handling` 으로 파이썬에서 어떻게 에러 처리를 하는지 찾아보고
장고에서는 어떤 에러들이 발생하는지 `django errors`로 검색하면 좋을듯

파이썬 에러 핸들링: https://docs.python.org/3/tutorial/errors.html
장고에서 제공하는 에러: https://docs.djangoproject.com/en/3.1/ref/exceptions/

```
try:
    result = Corp.object.get(~)
except 예외1 as err: # first expected error
    return (None, err)
except 예외2 as err: # second expected error
    return (None, err)
except Exception as e: # unexpected error
    return (None, err)
else: # succesful
    return (result, None)
```
이러면 함수의 반환값 첫번째 인자는 result, 두번째는 에러인데 이를 받는 곳에서 각 값에 따라 핸들링하고 에러가 발생했다면 무슨 에러인지도 exception을 받아오기 때문에 REST 핸들러에서도 어떤 status code를 반환할지 정할 수 있음.

2021-02-24 13:59 UTC, Jeldo commented on Backend/apps/financials/views.py
> +                    print("There is no matching query")
로그를 위한 거라면 python logging 모듈을 사용하는게 좋을듯
로컬에서 디버깅용으로 사용한 print는 항상 삭제해서 올려야함

2021-02-24 13:59 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        corporate_code = get_corporate_code(search_key)
위에 있는 report 생성쪽 알고리즘에 대해서는 주말에 리뷰하겠음

이제 views.py의 코드가 엄청 길어지고 있는데, CompanyLookUpView의 역할은 굉장히 많음.
역할을 풀어서 생각해보면
1. 프론트에서 request를 받아와서 파싱하는 부분
2. 파싱해서 얻은 값을 통해 실질적으로 기업 검색을 하는 부분

이 외에도 기능들이 조금씩 추가된다면 해당 클래스는 역할이 많아지게 되고 복잡해질텐데 어떻게 할까?

프로그래밍 원칙에는 여러가지가 있는데 SRP라는 키워드를 공부해보면 좋을 것 같고
2번은 이제 다른 파일(다른 모듈)로 빼내서 지금 views에서 import를 해서 사용하는 방식으로 만들고
1번에서는 request 파싱, 파싱 결과로 2번에 대해 요청 & 결과를 받아와서 에러 처리 및 response 전달
이런 구조로 만들면 좋을듯

2021-02-28 19:10 UTC, Jeldo requested changes

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        search_key = request.query_params["searchKey"]
변수 이름과 파라미터 이름을 더 신중하게 지을 필요가 있을 듯
"searchKey"는 너무나 일반적인 키값이 될 수 있음

파이썬 변수는 굳이 key를 안붙혀도 될 듯.

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/views.py
>          consolidation_key = request.query_params["consolidationKey"]
여기도

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/modules.py
> +            except Corporation.DoesNotExist as err1:
`A as B`는 python에서 B를 A의 별명으로 하겠다 이런 문법이라
```
except Corp.DoesNotExist as err:
    return err
==
except Corp.DoesNotExist
    return Corp.DoesNotExist
```
같은 결과를 보여줌. 그리고 err는 except 스코프에서만 사용되고 있어서 궅이 밑의 에러와 이름을 다르게 가져갈 필요없이 둘다 err로 해도 될듯

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/modules.py
> +    def get_corporate_code(key):
모든 클래스의 첫번째 파라미터에는 self가 있어야함

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        corporate_code = FinancialReport.get_corporate_code(search_key)
FinancialReport를 클래스로 정의했는데, 인스턴스 생성한 뒤 인스턴스를 사용하는 방식으로 만들지 않고 class function을 직접 가져와 사용하는 방식으로 되어있음.

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/views.py
> +from .models import Corporation
사용하지 않는 코드 삭제

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/modules.py
> +    def get_financial_statements(corporate_code, consolidation_key):
class읜 function 첫번째 parameter는 self

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/modules.py
> +        self.pastPriorPeriodAmount = past_prior_period_amount
instance varaible은 파이썬 변수니까 lower snake case를 사용하지 않고 underscore (_)를 사용함
request parameter의 key값으로 사용되는 string 값과 파이썬에서 사용할 변수를 구분하고 변수를 지정할 필요가 있음

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/views.py
>              consolidation_key = "OFS"
문자열 True / False를 받느냐에 따라 값이 이지선다라면 굳이 True/False가 아니라 입력값 자체를 CFS/OFS로 변경하는게 좋을듯

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/views.py
> +            return Response(data={"error: doesn't exist"}, status=status.HTTP_400_BAD_REQUEST)
위에서 에러 메세지를 정의했으면 `corporate_code == "error"`로 비교하는게 아니라 에러메세지가 반환되는지 확인하고 그에 맞는 status code와 메세지를 반환해야함

예를 들어 위에서
```
CorporateCodeNotFoundError= "corporate code not found"
...
def some_function():
    try:
        result = Corporation.objects.get(~~)
    except Corporation.DoesNotExist as err
        return err
    else:
        ....
```
이런 코드일 때 에러가 발생하게 된다면 `err`의 값은 Corporation.DoesNotExist이 되고 리턴이 될 것임.
그러면 이 에러를 받는 (try~catch가 정의된 함수를 호출한) 위치가 REST 핸들러라면
```
res = specific_function()
if res == Corporation.DoesNotExist:
    return Response(data={"message": res}, status=404)
```
이런 식으로 처리할 수 있을 것임

2021-02-28 19:10 UTC, Jeldo commented on Backend/apps/financials/modules.py
> +    def get_financial_reports(financial_statements):
self

2021-02-28 23:22 UTC, psymoney commented on Backend/apps/financials/views.py
> +        search_key = request.query_params["searchKey"]
파이썬 변수에 key를 안붙이는 특별한 이유가 있음? 
기본 라이브러리 같은데서 주로 사용된다던지하는

2021-02-28 23:41 UTC, psymoney commented on Backend/apps/financials/views.py
> +        corporate_code = FinancialReport.get_corporate_code(search_key)
인스턴스화를 통해서 FinancialReport 클래스 내 메서드를 활용하는게 권장되는 이유는 무엇임?
내가 아는선에서 생각해본 이유는 인스턴스화 하게되면 FinancialReport 클래스에 대한 직접적인 접근을 하지 않고, 인스턴스화를 통해 새로운 메모리를 할당 함으로써 클래스에 대한 영향을 없애려는 것임.

2021-03-01 00:50 UTC, psymoney commented on Backend/apps/financials/views.py
>              consolidation_key = "OFS"
이부분은 유저가 특정값을 입력하는게 아니라 토글식으로 하고 싶은데, 이렇게 적용하더라도 토글 전달값을 CFS/OFS로 해도 상관이 없는지?

2021-03-01 02:17 UTC, Jeldo commented on Backend/apps/financials/views.py
>              consolidation_key = "OFS"
프론트엔드에서 토글을 어떻게 처리하느냐에 따라 충분히 바뀔 수 있을듯
consolidation이 key인데 이거에 대한 value는 정하기 나름..

2021-03-01 02:30 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        search_key = request.query_params["searchKey"]
파이썬 변수라고 했는데 그냥 변수 네이밍의 문제라고 보면됨
계속 json key의 개념과 파이썬 내부에서 상사용되는 변수랑 혼동하는 것 같은데
`변수 = request.query_params[키]`
이렇게 받아올때 키는 json 형식에 맞춰야하고 변수의 이름은 아무렇게나해도 상관없는데 어떤 데이터가 들어갈지에 대해 네이밍을 하는 기본적인 컨벤션을 따르는 거
Json은 key:value 형식으로 되어있으니 엄밀히 말하면 '변수'에 들어가는 값도 key가 아니라 value고 지금 너가 정의한 상태의 네이밍 방식을 따른다면 그럼 모든 json의 value를 받아오는 변수 이름은 a_value b_value c_value 가 되는건데 어차피 어떤 '값'이 들어가는건 뻔하고 그 안에 들어가는 데이터의 의미를 나타내는 변수 네이밍이 더 중요해서 귿이 뒤에 _value를 뺀다는거임
마찬가지로 int 형 str형 변수 네이밍 할 때도 student_name_str 이런식으로 하지않고 student_name 이라고 하는것도 같은 이유.
굳이 타입에 대한 확인이 필요하다면 변수 이름에 타입을 붙이지말고 파이썬에도 타입힌트 기능이 있으니 구글링해보고 적용해보고 싶으면 적용하는거로..

2021-03-01 04:04 UTC, Jeldo requested changes

2021-03-01 04:04 UTC, Jeldo commented on Backend/apps/financials/views.py
>  from rest_framework.response import Response
render, request, Corporation, Report,  psycopg2, JSON 다 사용 안하는데 임포트 하고 있음

2021-03-01 04:04 UTC, Jeldo commented on Backend/bin/db_initializer.py
> +Initilize_Db()
사용하지 않는 위 코드와 corp.json 파일은 삭제
폴더에 데이터베이스를 위한 코드가 들어있으면 bin보다 db가 네이밍에 좀 더 좋을듯?

2021-03-01 04:04 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        lookup_value = request.query_params["lookupValue"]
lookup_value보다 그냥 `query`가 나을듯
키도 "query"로

기존 코멘트에 A_key, B_value, C_str, D_int 방식의 네이밍은 안좋다고 했는데 다시 _value를 하는 이유가 있는지..?

2021-03-01 04:04 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        corporate_code = report.get_corporate_code(lookup_value)
static method, class method 방식이 이 구현에 어울린다고 생각하면 사용해도 좋음
파이썬에는 instance method, class method, static method 3가지 클래스 내 함수 타입이 있는데
본인이 생각하기에 장단점을 따져서 적절한 방식으로 구현하면됨
다만 지금은 MVP를 구현해야하니 마이너한 퍼포먼스 이슈를 굳이 신경쓰지 않아서 instance 생성에 따른 오버헤드는 고려 대상이 아님

2021-03-01 04:04 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        if str(corporate_code) == 'Corporation matching query does not exist.':
기존 코멘트 수정하다가 잘못 업데이트가 되어서 정정함..

```
# modules.py 
CorporateCodeNotFoundError= "corporate code not found"
...
def some_function():
    try:
        result = Corporation.objects.get(~~)
    except Corporation.DoesNotExist
        return CorporateCodeNotFoundError
    else:
        ....
```
```
# views.py
    if corporate_code == CorporateCodeNotFoundError:
        return Response(data={"message": CorporateCodeNotFoundError}, status=status.HTTP_400_BAD_REQUEST)
```

2021-03-01 04:14 UTC, psymoney commented on Backend/apps/financials/views.py
> +        search_key = request.query_params["searchKey"]
음 타입을 붙인게 아니라 그냥 검색용 키값을 명명하면서 key랑 value를 쓴거라 json 형식 호출을 염두해서 한건 아니긴했음..ㅎㅎ

2021-03-01 04:41 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        lookup_value = request.query_params["lookupValue"]
https://google.github.io/styleguide/pyguide.html#3161-names-to-avoid
3.16.1 5번째

2021-03-01 04:49 UTC, Jeldo commented on Backend/apps/financials/views.py
> +                financial_statements)
else 안에서 reports를 생성하고 바깥에서 return 하고 있음
위의 조건문을 충족하지 않으면 언제나 else이므로 굳이 else를 사용할 필요가 없음
파이썬은 블록 scope가 독특해서 이렇게 코드를 작성해도 코드가 작동은 하지만 가독성을 위해서 else 삭제가 좋을듯

2021-03-01 05:13 UTC, Jeldo approved these changes

2021-03-01 05:14 UTC, psymoney commented on Backend/apps/financials/views.py
> +        corporate_code = report.get_corporate_code(lookup_value)
https://dodonam.tistory.com/122
참고하기

2021-03-01 05:14 UTC, merged