Issue#25 add user table
psymoney/stocker pull request #29
Opened 2021-03-02 04:14 UTC by psymoney

Close #25

2021-03-02 05:08 UTC, Jeldo requested changes

2021-03-02 05:08 UTC, Jeldo commented on Backend/.idea/.gitignore
> +/workspace.xml
/idea 경로는 pycharm에서만 사용하는 파일들이므로 gitignore에 추가

2021-03-02 05:08 UTC, Jeldo commented on Backend/apps/user/models.py
> +    id = models.IntegerField(primary_key=True, max_length=255)
integer type인데 max_length는 왜 넣었는지?
PK로 사용되는 int형 id를 위한 필드는 장고에서 AutoField를 제공하고있음
https://docs.djangoproject.com/en/3.1/ref/models/fields/#field-types 참고

2021-03-02 05:08 UTC, Jeldo commented on Backend/apps/user/tests.py
> +# Create your tests here.
사용하지 않는 모듈 삭제

2021-03-02 07:24 UTC, Jeldo requested changes

2021-03-02 07:24 UTC, Jeldo commented on Backend/.idea/Backend.iml
> +</module>
introduction git 슬라이드에서 squash 하는 방법 알아보고
.idea 경로의 파일들까지 add된 커밋이랑
gitignore 업데이트한 커밋이랑 squash 해서 force push
squash는 `git rebase -i HEAD~#`
#은 HEAD에서부터 몇번째 커밋까지 합칠지 숫자로 나타내면됨
위에서부터 2개라면 2
자세한건 더 찾아보고

2021-03-02 07:24 UTC, Jeldo commented on Backend/apps/user/models.py
> +    id = models.AutoField()
pk가 명시적으로 되어있지 않을때 autofield를 정의하면 장고에서 자동으로 autofield에 pk를 정의해주지만 코드에는 명시해주는 것이 좋음.

2021-03-02 08:11 UTC, psymoney commented on Backend/.idea/Backend.iml
> +</module>
완료

2021-03-02 08:31 UTC, Jeldo approved these changes
LGTM

2021-03-02 08:32 UTC, Jeldo requested changes

2021-03-02 08:32 UTC, Jeldo commented on Backend/apps/user/urls.py
> +    path('user/', views.SigninView.as_view()),
최종 URI가 user/user가 될텐데 signin에 적합하다 생각하는지?
signup, in 은 각각 어떤 URI로 될건지 정리해서 design doc에 정의부터 제대로 하고 다시 PR 수정 진행합시다

2021-03-03 02:29 UTC, Jeldo approved these changes
LGTM

2021-03-03 02:39 UTC, merged