Add user services
psymoney/stocker pull request #32
Opened 2021-03-04 12:24 UTC by psymoney

Close #28

2021-03-04 13:34 UTC, Jeldo requested changes

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/views.py
> +        password = login_information["password"]
email = request.data["email"]
password = request.data["password"]
로 간단하게 변수 할당가능할듯
복잡한 객체에서 가져오는게 아니면 굳이 별도의 변수를 만들 이유가 없어보임

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/views.py
> +        result = SignInService.sign_in(self, email, password)
구현은 instance method 방식으로 했는데 실제 사용은 SignInView의 객체 자신을 가리키는 self를 첫번째 parameter로 넘겨주고 있음. 이전에도 이 부분에 대해서 코멘트를 남겼었는데 혹시 instance method, class method, static method를 구분해서 사용하고 있는건지?
이 부분이 헷갈리면 굳이 class method, static method 방식은 사용하지 말고 언제나 instance 생성한 뒤 instance method를 호출하는 방법이 나을듯.

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_in_service.py
> +            return AuthenticationFailure
service와 view에서의 status code를 보면
frontend에서는 유저가 없는 경우에는 'Failure' 라는 메세지와 409를 받게 될텐데
해당 email의 유저가 없다는 것을 판단할 수 있는지?
user not found error의 경우엔 404가 더 적합함. 409는 PUT(update) 메소드를 사용한 request가 현재 리소스 상황과 충돌일 때인데 user not found 와는 맞지 않음.
https://stackoverflow.com/questions/5604816/whats-the-most-appropriate-http-status-code-for-an-item-not-found-error-page
어떤 status code를 사용해야될지 모르겠으면 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404 이 페이지를 비롯해 어떤 상황일 때 어떤 status code를 반환하는지 적혀있으니 참고하고, 상황이 애매하다 싶으면 구글링해서 다른 사람들은 어떤 코드를 반환했는지 검색해보면 좋을듯.

AuthenticationFailure -> UserNotFoundError = 'user not found'

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_in_service.py
> +            return AuthenticationFailure
wrong password는 403반환과 함께 어울리는 에러 메세지를 작성하는게 좋음

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_in_service.py
> +        return True
비정상 요청인 경우에는 모두 에러를 리턴하기 때문에 굳이 boolean 값을 리턴하고 이를 view에서 확인하지 말고 정상인 경우엔 None을 리턴하고 view에서는 sign_in의 결과를 error로 받은 다음 에러가 있냐 없냐에 따라 응답을 주면 될 듯

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +        def duplication_check(email):
함수는 동사형으로 시작하고 다른 명사형으로 명명된 함수도 변경

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +        def validity_check(email, user_name, password):
name은 이름이 영어인 사람은 20글자 넘을 수 있는데 이름길이에 대한 제한은 일반적인 서비스에서는 잘 없는듯
패스워드도 최소길이에 대한 제한은 있되, 최대길이에 대한은 잘 없음

하나의 함수가 여러 역할을 하는데 이거보단 validate_email, validate_password로 나눈 다음 하나라도 통과가 안되면 바로 리턴을 하게하면 더 빠르게 리턴 가능함

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/views.py
> +        return Response(data={"message: ": result}, status=status.HTTP_409_CONFLICT)
서비스에서 정의한 모든 에러에 대해 똑같은 409에러를 반환하고 있음. 각 에러에 대해 적절한 status code를 찾아서 문서에 정의하고 구현해야함

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/views.py
> +        result = SignUpService.sign_up(self, email, user_name, password)
sign in service에도 코멘트 했듯이 할당 받는 변수를 error내지 err로 하고 이를 확인해서 적절한 status code를 반환해줘야함. 200에 대한 리턴은 보통 제일 마지막에 하는 것이 깔끔함.

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +InvalidPasswordError = 'Invalid password'
에러 메세지는 소문자로 시작해서 마침표 없이

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +                return InvalidPasswordError
파이썬에서는 boolean 체크를 ` if x == True ` 로 하지 않고 `if x `혹은 ` if not x` 로 하는 것이 컨벤션

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +                return DuplicateEmailExistError
어차피 가입할 때 있는지 없는지 체크를 하게될텐데 미리 중복 fixture값을 넣지 않는 이상 duplicate email 이 발생할 수 있는 로직이 없을듯

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +            return DuplicateEmailExistError
이 로직인 경우 위에 정의한 exception이 아닌 예상하지 못한 exception인 경우엔 무조건 DuplicateEmailExistsError를 반환하는데, 이런 경우엔 "error while creating user" 같은 메세지를 반환하는게 좋을듯
```
except User.DoesNotExist:
    return None
except Exception as err:
    return f"{err} error while creating user for user email={email}"
```

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +InvalidEmailError = 'Invalid email'
invalid email format이 더 좋은 에러 메세지일듯

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/views.py
> +        password = user_information["password"]
request.data["email"]
request.data["userName"]
request.data["password"]

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +        duplication = duplication_check(email)
email, name, password를 validation을 하고나서 duplicate 체크를 하는데 반대 순서로하면 중복 이메일이 있을 경우엔 더 빠르게 반환할 수 있을듯

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +            User.objects.create(email=email, user_name=user_name, password=password)
https://docs.djangoproject.com/en/3.1/topics/db/queries/#creating-objects 참조
model instance는 만들고 db에 저장을 안하고 있는데 create만 해도 db 저장이 되는지 확인 했는지?

2021-03-04 13:34 UTC, Jeldo commented on Backend/apps/user/views.py
> +class SigninView(APIView):
토큰은 넘겨주고 있지 않은데 sign in 할 때 넘겨주는걸 마저 구현해야 할 듯

2021-03-04 13:35 UTC, Jeldo requested changes

2021-03-04 13:35 UTC, Jeldo commented on Backend/server/urls.py
> +    path('api/token/refresh', TokenRefreshView.as_view(), name='token_refresh')
구현하지 않은 path 삭제

2021-03-05 01:03 UTC, psymoney commented on Backend/apps/user/services/sign_up_service.py
> +                return DuplicateEmailExistError
테스트하면서 포스트맨으로 여러번 요청 눌렀는데 같은 계정 두개가 생성됐고, 그래서인지 저 익셉션이 발생했음.
이런 이유로 반영하긴 했는데 어떻게 해야할까

2021-03-05 01:04 UTC, psymoney commented on Backend/apps/user/services/sign_up_service.py
> +                return DuplicateEmailExistError
아래 의견이 있구나 확인했음

2021-03-05 04:07 UTC, Jeldo requested changes
Merge after resolving PR comments

2021-03-05 04:07 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +        def duplication_check(email):
동사형으로

2021-03-05 04:07 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +        if duplication:
함수 리턴값으로 바로 확인가능할듯

2021-03-05 04:07 UTC, Jeldo commented on Backend/apps/user/services/sign_up_service.py
> +        User.objects.create(email=email, user_name=user_name, password=password)
create할 때 db쪽에서 발생하는 예상치 못한 exception에 대한 핸들링도 필요함

2021-03-05 04:07 UTC, Jeldo commented on Backend/apps/user/views.py
> +        signup = sign_up_service.SignUpService()
`sign_up_service = sign_up_service.SignUpService()`

2021-03-05 04:07 UTC, Jeldo commented on Backend/apps/user/views.py
> +        login = sign_in_service.SignInService()
`sign_in_service = sign_in_service.SignInService()`

2021-03-05 04:07 UTC, Jeldo commented on Backend/apps/user/views.py
> +        return Response(data={"Success"}, status=status.HTTP_200_OK)
토큰 서비스를 구현하면 토큰을 보내주게 될텐데, 코멘트로 자세히 써놓아야하고,
data에 불필요한 response body는 필요없을듯

2021-03-05 05:19 UTC, psymoney commented on Backend/apps/user/views.py
> +        signup = sign_up_service.SignUpService()
이렇게 하니까 import 한 sign_up_service 파일이랑 네이밍이 겹쳐서 오류 나오는데 import as 별칭으로 처리해서 하면 되는지?

2021-03-05 06:25 UTC, merged