Add token service
psymoney/stocker pull request #34
Opened 2021-03-06 01:03 UTC by psymoney

Close #30

2021-03-06 02:02 UTC, Jeldo requested changes

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +        token = jwt.encode({"email": email}, SECRET_KEY, algorithm=ENCRYPTION_ALGORITHM).decode('utf-8')
payload = {"email": email}
token = jwt.encode(payload=payload, key=SECRET_KEY, ...) 가 나을듯
utf-8 디코딩은 왜 하는지?

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +            email = jwt.decode(token, SECRET_KEY, algorithms=ENCRYPTION_ALGORITHM)["email"]
```
payload = jwt.decode(jwt=token, key=SECRET_KEY, ...)
email = payload["email"]
```

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +            return err
view에서는 두 에러에 대해 500에러를 발생시키는데
token의 값이 부적절한 원인에 따라 발생되는 에러인데 500은 적절하지 않음
token이 이상하다는건 client의 입력이 이상하다는건데 view에서 수정이 필요할듯

payload까지는 맞는데 signature가 변조된 token 의 요청에 대한 핸들링도 필요함
또한 알 수 없는 jwt에러가 날 때 500을 반환해야할듯

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +            return AuthorizationDeniedError
user not found면 not found에 관한 에러를 발생시키고 404를 줘야할듯

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/user/views.py
>          password = request.data["password"]
body에 해당 field가 오지 않는 경우에 대한 핸들링 필요

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/user/views.py
>          password = request.data["password"]
여기도

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/user/views.py
> +        access_token = token_service.create_token(request.data["email"])
위에서 email이라고 정의를 했는데 다시 request에서 불필요하게 가져오고 있음

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        token = request.headers['Authorization'].split()[1]
1. 헤더에 auth 필드가 없다면
2. auth 필드에 `bearer abc` 형식의 문자열이 안온다면?
위에 대한 핸들링 필요
client의 request에 대해 파싱하고 에러 핸들링하는건 view 내부에 있는 각각의 get/post 등등의 API 핸들러의 책임

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/financials/views.py
>          consolidation = request.query_params["consolidation"]
query parameter에 해당 필드값이 없거나 잘못된 값에 대한 핸들링 필요

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        verification = token_service.verify_token(token)
왼쪽에 할당되는 결과가 에러 or None인데 verification은 적절하지 않은 변수명인듯

2021-03-06 02:02 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +ENCRYPTION_ALGORITHM = 'HS256'
나중에 config파일로 옮겨야함

2021-03-06 02:24 UTC, psymoney commented on Backend/apps/user/services/token_service.py
> +        token = jwt.encode({"email": email}, SECRET_KEY, algorithm=ENCRYPTION_ALGORITHM).decode('utf-8')
디코딩 안하면 byte 값으로 반환됨

2021-03-06 04:40 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +        token = jwt.encode({"email": email}, SECRET_KEY, algorithm=ENCRYPTION_ALGORITHM).decode('utf-8')
![Screen Shot 2021-03-06 at 1 39 03 PM](https://user-images.githubusercontent.com/37772279/110195554-52cd4f80-7e81-11eb-9245-f069740eba50.png)
encode 함수 따라가보면 최종적으로 utf-8로 내부에서 디코드해서 줘서 str 타입이 반환되고,
위 코드라면 str에서 decode를 하게되어 에러날 것 같은데 확인된거임?

2021-03-06 23:32 UTC, psymoney commented on Backend/apps/user/services/token_service.py
> +        token = jwt.encode({"email": email}, SECRET_KEY, algorithm=ENCRYPTION_ALGORITHM).decode('utf-8')
ㅇㅇ 디코드 안할때 byte 반환으로 에러나고 디코드 한 코드는 에러없이 잘 작동함

2021-03-07 00:29 UTC, psymoney commented on Backend/apps/financials/views.py
>          consolidation = request.query_params["consolidation"]
필드 값이 없거나 잘못된 경우 검색 결과에서 해결되는게 아닌지?

2021-03-07 02:41 UTC, Jeldo requested changes

2021-03-07 02:41 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        print(query_parameters)
불필요한 로깅 삭제

2021-03-07 02:41 UTC, Jeldo commented on Backend/apps/financials/views.py
>          consolidation = request.query_params["consolidation"]
Http 요청에 대해 에러를 확인하고 핸들링하는건 view의 역할이고 query param을 받아서 처리만 하는건 해당 서비스의 역할이라 리포트 서비스가 쿼리파라미터가 있는지없는지 확인하는건 역할이 많은 것.
파싱해서 넘겨준 값 자체에 대해서 핸들링하는건 서비스의 책임은 맞음.

2021-03-07 02:41 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +        payload = {"email": email}
`{ "email": email }`
괄호와 문자열 사이 공벡이 필요함.

https://google.github.io/styleguide/pyguide.html
3.6. Whitespace

Python convention은 구글 스타일 가이드 참조하고, 어지간한 인덴트 문제는 auto intentation 단축키로 해결가능함. Pycharm에서 지원하니까 단축키는 구글링하면 될듯

2021-03-07 02:41 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +        token = jwt.encode(payload, SECRET_KEY, algorithm=ENCRYPTION_ALGORITHM).decode('utf-8')
jwt.encode, decode를 추적해보면 최종 리턴값의 type은 str으로 명시되어있는데 pyjwt 1.7.1 에선 해당 decode시 byte로 나오는 문제가 있었고, 2.0.0+ 버전에서 해결되었다함. 해당 라이브러리 업데이트하면 충돌없을듯

2021-03-07 02:41 UTC, Jeldo commented on Backend/apps/user/views.py
> +
```
body = request.data
if "email" not in body.keys() or "password" not in body.keys():
    Response(data={"message: ": "malformed body request"}, status=status.HTTP_404_NOT_FOUND)
```
django restframework의 request에서 request.data하면 파디를 파싱해줘서 dict 타입으로 리턴을 해주고 있어서 디코드를 안해도 될듯

sign up도 마찬가지

2021-03-07 02:41 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        query_parameters = request.query_params
쓰지 않는 변수 삭제

2021-03-07 02:41 UTC, Jeldo commented on Backend/apps/financials/views.py
> +            return Response(status=status.HTTP_403_FORBIDDEN)
서비스에서 해당 에러를 반환하는 경우가 없음

2021-03-07 02:41 UTC, Jeldo commented on Backend/apps/financials/views.py
> +        elif authorization_result == tokenservice.ExpiredSignatureError:
jwt.exceptions.ExpiredSignatureError
Raised when a token’s exp claim indicates that it has expired
https://pyjwt.readthedocs.io/en/stable/api.html#jwt.exceptions.ExpiredSignatureError
exp claim 사용하지 않아서 발생하지 않을 것 같은데 확인했는지?

2021-03-07 04:51 UTC, psymoney commented on Backend/apps/user/services/token_service.py
> +        payload = {"email": email}
No whitespace inside parentheses, brackets or braces.
style guide 우선 적용하겠음

2021-03-07 05:51 UTC, psymoney commented on Backend/apps/user/views.py
> +
request.body 리턴 타입이 bytes라 디코딩 없이 if문으로 넘어가면 typeerror 발생해서 디코드 없이 하기 힘들어 보임미다

2021-03-07 08:31 UTC, Jeldo requested changes

2021-03-07 08:31 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +        payload = {"email": email}
공백 관련 컨벤션이 다른 언어랑 혼동이 있었는데 이 부분 무시하고 문서에 맞춰 진행하면 됨

2021-03-07 08:31 UTC, Jeldo commented on Backend/apps/user/views.py
> +
애초에 body의 값들을 가져올 때 request.body로 직접 바이트를 가져오는게 아니라 프레임워크에서 파싱을 해서 가져온 값인 request.data로 가져와서 필드 존재 유무를 체크하면 되서 디코드가 필요없다는 뜻

2021-03-07 10:16 UTC, Jeldo approved these changes

2021-03-07 10:52 UTC, merged