Add favorite model and services
psymoney/stocker pull request #36
Opened 2021-03-09 05:10 UTC by psymoney

Close #27

2021-03-09 14:38 UTC, Jeldo requested changes

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +    def return_email(self, token):
`parse_token` 이라는 function으로 return이 payload로 하고 이 function을 사용하는 곳에서 payload의 특정 claim을 추출해서 사용하면 좀 더 일반적인 함수가 될듯

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(data={"message:  data not given"}, status=status.HTTP_400_BAD_REQUEST)
"malformed request" 혹은 "invalid request" 정도가 적당한 메세지일듯

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +        email = token_service.return_email(token)
token_service에서 구현부 코멘트 참조

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +    def delete_favorite(self, email, corporate_name, corporate_code, consolidation):
design doc 누락

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +    def check_duplicate(self, email, corporate_name, corporate_code, consolidation):
즐겨찾기에 대한 중복 검사가 필요한지 생각해봐야하는데, 일반적인 서비스들을 보면 유저가 즐겨찾기에 같은 데이터를 넣어도 들어가듯이 중복이 이 서비스에 크리티컬한 영향을 주지 않는다면 굳이 서버에서 중복검사가 필요한가 싶음.
웹 브라우저의 즐겨찾기 기능을 생각해보면 중복 URL을 저장한다고 해서 문제가 발생하지 않고, 이를 허용하듯 이 서비스에서도 허용하는 것도 나쁘지 않을듯.
기술적 문제라기보단 기획의 문제니 본인의 생각에 맞추면 될 것 같음.

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +                                 consolidation=consolidation)
join으로 하나의 쿼리로 만들 수 있을듯

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +            return DoesNotExistError
view에서 token payload의 email claim을 확인하고 있어서 User DoesNotExist Exception이 발생할 것 같지 않아서 favorite service 내부에서 굳이 다시 확인할 필요가 없을 것 같음.

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +            return DoesNotExistError
여기도

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +            return DoesNotExistError
여기도

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +        # TODO(SY): study on relational db function, 'join'
코드 외적인 것에 대한 코멘트는 삭제하고 별도의 노트에서 정리
django ORM table join 키워드로 검색해보면 될듯

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +            return f"{err} error while deleting favorite"
잘못된 에러 메세지 수정

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +class FavoriteReport:
FavoriteReport는 'Report'에 대한 class니까 report 내용이 들어갈 것 같은 class인데 막상 field는 params라 부적절한 class naming같음.
Favorite model을 import하면서 이름이 가려지는 문제 때문에 그렇다면
`from ..models import Favorite as FavoriteModel` 등 다른 별명으로 import하거나 FavoriteReport의 이름을 다른 이름으로 더 정확하게 변경하는 방법이 있을듯

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +        email = token_service.return_email(token)
구현부 참조

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(status=status.HTTP_403_FORBIDDEN)
메세지 없음

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR)
메세지 없음

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(status=status.HTTP_404_NOT_FOUND)
유저의 즐겨찾기가 없다면 그냥 빈 리스트를 반환하는 것이 스탠다드
실제로 즐겨찾기가 비어있다면 404 not found가 아니라 "즐겨찾기 목록이 비어있습니다" 정도로 유저에게 안내하듯 404로 처리하면 안될듯함

2021-03-09 14:38 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR)
메세지

2021-03-10 03:08 UTC, psymoney commented on Backend/apps/favorite/services/favorite_service.py
> +    def check_duplicate(self, email, corporate_name, corporate_code, consolidation):
현재 즐겨찾기 대상을 다시 저장하면 즐겨찾기에서 삭제되는 방법을 구현하고 있어서 즐겨찾기에 대한 중복검사는 필수적으로 필요할 것으로 판단하였음. 중복적인 즐겨찾기 저장에서 오늘 불편함이 특별히 존재하진 않지만 존재한다고 해서 특별한 ux를 창출할 것 같지도 않다는 것이 내 생각.

2021-03-10 03:11 UTC, psymoney commented on Backend/apps/favorite/services/favorite_service.py
> +    def delete_favorite(self, email, corporate_name, corporate_code, consolidation):
이런 서비스의 method는 design doc의 어느 부분에 반영을 하면 되는지?
API 개요에서는 request와 response 만 정의 하다보니 이를 위해 구현해야하는 method 들이 나타나질 않는데 어떤 식으로 반영해 주면 될까

2021-03-10 07:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +    def delete_favorite(self, email, corporate_name, corporate_code, consolidation):
delete favortie API를 만드는줄 알았는데 create을 할 때 delete를 하려는지는 이제 봤네
밑에 코멘트 참조하면될듯

2021-03-10 07:38 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +    def check_duplicate(self, email, corporate_name, corporate_code, consolidation):
중복이면 삭제하고 만드는게 아니라 중복 에러를 반환하고 안만드는게 맞지 않을까

2021-03-10 09:02 UTC, psymoney commented on Backend/apps/favorite/services/favorite_service.py
> +    def check_duplicate(self, email, corporate_name, corporate_code, consolidation):
중복이라 삭제하고 만드는게 아니라 걍 삭제만 시키는거임.
토글로 생각하면 될듯

2021-03-10 09:05 UTC, psymoney commented on Backend/apps/favorite/services/favorite_service.py
> +    def delete_favorite(self, email, corporate_name, corporate_code, consolidation):
아래 코멘트가 어디에 있는지..?

2021-03-10 12:13 UTC, Jeldo requested changes

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +            return DoesNotExistError
여기도 유저에 대한 에러 반환 필요

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +DoesNotExistError = 'list does not exist'
UserNotFoundError = "user not found"
FavoriteNotFound = "favorite not found"
와 같은 에러 정의가 더 적절할듯
에러의 경우 어느 Entity에 관련된 Error인지 에러 명에 명시를 해야 사용하는 쪽에서 알기 쉬움
NotFoundError 라고 하면 이게 User에 대해서인지 Favorite에 대해선지 변수명만으로 판단할 수 없기 떄문에
UserNotFoundError 혹은 FavoriteNotFoundError가 더 좋은 네이밍임
DuplicateExistsError도 FavoriteAlreadyExistError가 더 좋은 네이밍

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +        is_duplicate = favorite_service.check_duplicate(email, body['corporateName'], body['corporateCode'], body['consolidation'])
is XXX 이라는 변수는 bool 값을 가져와야함
check_duplicate function은 str 형태의 에러 메세지 혹은 None을 반환하는데 리턴 타입을 고치는 것이 좋을듯.

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +        return Response(status=status.HTTP_200_OK)
https://cloud.google.com/apis/design/standard_methods#create
POST Method는 resource의 Create에 관련된 것이어야하는데 이 핸들러에서는 Create과 Delete를 같이 하고 있음
즐겨찾기 추가 -> Create Favorite
즐겨찾기 삭제 -> Delete Favorite
로 각각의 API에서 구현되어야함.

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +    def delete_favorite(self, email, corporate_name, corporate_code, consolidation):
Conversation에서는 순서가 바뀌는데 이 코멘트는 무시하면됨 view쪽에 정리하겠음

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +    def check_duplicate(self, email, corporate_name, corporate_code, consolidation):
view쪽에 정리하겠음

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +        return Response(status=status.HTTP_200_OK)
1. 제안한 토글 방식의 UI Mock up 구현
- figma에서는 '저장'이라고 되어있는데 저장을 두 번 누르면 즐겨찾기 해제가 되는데 이게 적절한 UI인지 생각해봐야함
- '저장'을 눌렀는데 삭제가 되는 flow는 굉장히 어색한 UX
- 토글 방식으로 한다면 아이콘 방식(☆/★) 혹은 스위치 방식 등등 으로 On/Off 에 대한 구분이 되는 UI를 만들어야함
2. 위에서 정한 방식에 따른 UX Flow 변경사항 수정
3. 즐겨찾기 추가/삭제에 따른 각각의 API를 Design Doc에 작성 
4.. 코드 구현

3번까지 되기 전까지는 코드 구현하지 말고 꼼꼼하게 설계해야함.
1~3과정이 먼저 잘되어야 4번도 쉽고, 리뷰어도 코드 의도를 알 수 있음.

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +            return f"{err} error while calling favorites"
error while getting favorites

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +        favorites = []
favorites -> result
favorite_group -> favorites

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +        for favorite in favorite_group:
```
for f in favorites:
  favorite = Favorite(...)
```

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +    def return_claim(self, token, claim):
```
def get_payload(self, token):
   ...
   return payload
```
당장 여기서는 하나의 claim만을 가져오기 때문에 지금과 같은 function으로 해도되지만
payload 전체를 가져와서 claim을 선택하는 것은 함수 호출한 곳에서 처리하면 되므로 이런 방식이면 좀 더 일반적인 함수가 될 것

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
> +        return payload
parse_token은 `return_claim`에서만 사용하고 있는데  이미 핸들러에서 verify했기 때문에 토큰의 유효성 검사를 다시 할 필요없이 payload만 가져오면됨. 
https://pyjwt.readthedocs.io/en/stable/usage.html#reading-the-claimset-without-validation
위 방법 통해서 return claim에서 payload만 가져오면 될듯

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/financials/views.py
>              return Response(data={"message:  data not given"}, status=status.HTTP_400_BAD_REQUEST)
2 spaces  -> 1 space

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR)
메세지 없음

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +        favorites = favorite_service.get_favorites(email)
`result = favorite_service.get_favorites(email)`
favorites가 될 수도 있고 에러도 될 수 있으니 더 나은 이름일듯

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(data={"message: empty favorite list"}, status=status.HTTP_200_OK)
LIST에 해당하는 API에 대해 결과값이 없다면 빈 리스트를 주면 됨
지금 get_favorites에서도 favorite이 없다면 빈 리스트를 반환하도록 본인이 작성했는데
여기서는 발생할 수 없는 에러에 대해 처리하고있음.

https://stackoverflow.com/questions/13366730/proper-rest-response-for-empty-table

2021-03-10 12:13 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +        elif favorites is type(str):
에러 메세지를 받았을 때인데 이 방식보다 더 좋게 에러임을 확인하는 방식이 필요함.
에러 메세지가 아니라 error 객체를 직접 만들거나 관련 라이브러리가 있으면 적용하면 될듯함.
P2정도로 하고 개선하면 될듯

2021-03-10 13:34 UTC, psymoney commented on Backend/apps/favorite/services/favorite_service.py
> +DoesNotExistError = 'list does not exist'
감사합니다 한층 더 배웁니다

2021-03-11 05:29 UTC, psymoney commented on Backend/apps/user/services/token_service.py
> +    def return_claim(self, token, claim):
그렇다면 pares_token 만으로 payload 리턴이 가능하니 return_claim 기능은 존재하지 않아도 된단거겠네?

2021-03-11 12:44 UTC, Jeldo requested changes

2021-03-11 12:44 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +UserNotFound = 'user not found'
UserNotFoundError

2021-03-11 12:44 UTC, Jeldo commented on Backend/apps/favorite/services/favorite_service.py
> +            favorite = Favorite(favorite.id, favorite.corporate_name, favorite.corporate_code, favorite.consolidation)
for loop의 iterable element 이름과 생성된 Favorite 객체 이름이 같아서 혼동될텐데
```
for f in favorites:
  favorite = Favorite(f.id, ...)
```
이런 방식으로 하거나 f 대신 element 등등 element의 이름을 변경하는게 좋을듯

2021-03-11 12:44 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +        email = token_service.parse_token(token)['email']
지금과 같은 경우엔 claim 하나만 사용하기 때문에 key값을 붙여서 사용해도 별 문제는 없지만
payload 전체를 반환하는 함수를 사용할 때는
```
payload = ~~
email = payload['email']
```
이런식으로 받아오는 것이 일반적

2021-03-11 12:44 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(status=status.HTTP_403_FORBIDDEN)
에러 메세지가 없다고 코멘트를 2번 달았는데, 계속 해결은 안하고 resolve 처리하는 것은 메세지가 필요없다는건지? 다른 생각이 있다면 최소한 어떻게 하겠다고 언급은 하고 resolve를 해야함. 2번 연속 실수로 닫았거나 아니면 리뷰어의 코멘트를 무시하는 의도 밖에 안됨.

2021-03-11 12:44 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(data={"message:  invalid request"}, status=status.HTTP_400_BAD_REQUEST)
double space
`malformed request`가 좀 더 친절한 에러 메세지일듯

2021-03-11 12:44 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +        email = token_service.parse_token(token)['email']
parse_token 결과로 None 올 수도 있는데 이에 대한 핸들링이 필요함

2021-03-11 15:06 UTC, psymoney commented on Backend/apps/favorite/views.py
> +            return Response(status=status.HTTP_403_FORBIDDEN)
뭐지.. 메세지 없는거 처리했는데 여러군데 있어서 헷갈린듯함. 그런 의도는 전혀 없었음...

2021-03-12 13:14 UTC, psymoney commented on Backend/apps/favorite/views.py
> +        email = token_service.parse_token(token)['email']
parse_token 이전에 verify_token 이용해서 payload 내부에 email이 User db내에 존재하는지까지 확인 이후에, parse_token이 진행되는데 parse_token이 None으로 오는 경우는 없을 것으로 판단됩니다.

2021-03-15 11:55 UTC, Jeldo requested changes

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +        email = token_service.return_claim(token, 'email')
parse_token으로 정의했으면 여기도  변경해야함

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(data={"message: an error occurred while verifying token"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
80자 이상은 개행하는게 컨벤션

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            creation_result = favorite_service.create_favorite(email, body['corporateName'], body['corporateCode'], body['consolidation'])
여기도 개행 필요.
Pycharm 사용중이면 auto formatting 기능 사용하면 알아서 해줄거임

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(data={"message: an error occurred while verifying token"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
여기도 새로운 메세지 불필요

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/financials/views.py
> +            return Response(data={"message: an error occurred while verifying token"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
여기도 굳이 새로운 메세지 작성 필요 없음

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(data={"message: an error occurred while verifying token"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
verify_token에서 정의되지 않은 Exception은 "{err} error while verifying token" 이라는 메세지를 전달해주므로 새롭게 메세지를 작성할 필요없이 반환되는 값을 메세지에 넣어주면됨
verify_token에서 정의되지 않은 예외일 때 어떤 값을 반환하는지 확인해야함

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(data={"message: consolidation not provided"}, status=status.HTTP_400_BAD_REQUEST)
에러 메세지를 모듈 상단에 정의하고 사용하는게 나을듯

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(status=status.HTTP_400_BAD_REQUEST)
메세지 없음

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(status=status.HTTP_400_BAD_REQUEST)
메세지 없음

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(status=status.HTTP_400_BAD_REQUEST)
메세지 없음

2021-03-15 11:55 UTC, Jeldo commented on Backend/apps/favorite/views.py
> +            return Response(data={"message: ": result}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
Internal Server Error의 경우에는 서버 내부의 에러 메세지를 외부에 노출시키면 안됨.
따라서 message는 "Internal Server Error" 와 같은 메세지를 주되,
 에러 메세지를 콘솔에 출력하는 방식으로 로깅을 하고 이를 통해 서버 내에서 에러를 추적할 수 있게 해야함

2021-03-16 11:21 UTC, Jeldo requested changes

2021-03-16 11:21 UTC, Jeldo commented on Backend/apps/user/services/token_service.py
>          return None
verify_token의 역할은 토큰을 verify하는 것만 있어야함
이름도 verify보다는 validate가 맞을듯
token service니까 굳이 prefix/suffix로 token 붙일 필요없이
create, validate 정도로 하고 각 함수의 역할은 하나만 하는 것으로 하고
user에 대한 체크는 외부에서 해야함

2021-03-29 09:32 UTC, Jeldo approved these changes

2021-03-30 05:18 UTC, merged