add sign in page
psymoney/stocker pull request #59
Opened 2021-04-09 15:53 UTC by psymoney

## PR Checklist
### PR settings
- [ ] base branch 확인
- [ ] Issue 링크 확인
### Code Quality
- [ ] 불필요한 코드 또는 미사용 코드가 없는가?
### Operation
- [ ] 코드의 변경 의도가 검증되었는가?
### Javascript
- [ ] 예측하지 못하는 에러들이 래핑되어서 핸들링되는가?
- [ ] Convention이 [Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html)를 따르는가?
closed #47

2021-04-09 18:18 UTC, Jeldo requested changes
src
|--adapter
|--components
|--pages

이런식으로 프로젝트 구조를 나누어서
adapter에는 API 관련
components에는 component
pages에는 navigation 관련된 것들로 나누어서 관리하고, 백엔드에서 모듈화를 했듯이 프론트에서도 해서 각 파일에 모든 것을 담지 말아야함.
`react project structure` 같은 키워드로 구글링하면 좋은 예제들이 많음

package.json에 axios, react-bootstrap 누락되어있음

PR Checklist를 형식적으로 체크하는 것이 아니라 해당 PR에 문제가 없는지 본인이 변경한 코드들을 PR전에도 확인하고 PR 이후에도 File Changed에서 한줄한줄 봐야함.
> 불필요한 코드 또는 미사용 코드가 없는가?

console.log는 디버깅할 때 잠시 로그를 볼 때 사용하고, 에러를 콘솔에 남기기 위해서는 console.error를 사용해야함. 따라서 console.log를 통해 불필요한 로깅하는 부분들은 삭제해야함.

> 코드의 변경 의도가 검증되었는가?

테스트를 통해서 검증을 해야하는데 유닛 테스트가 없으면 E2E테스트를 직접해보면서라도 검증해야함. 위에서 언급한 singin 오타 때문에 signin 페이지로 가는 것이 불가능한데 이 부분은 테스트 되지 않은 것 같음.

> Convention이 Google JavaScript Style Guide를 따르는가?

google style guide를 읽어보면서 convention이 어떻게 되는지 훑어보고 모르는 것들은 아무렇게나 정하는게 아니라 최대한 컨벤션에 맞게 정의해야함.

앞으로 구현하면서 필요한 대부분의 컴포넌트(버튼, 폼 등등)들은 [Material UI](https://material-ui.com/)에서 라이브러리로 제공함. react-bootstrap을 사용해도 되고 Material을 사용해도 되고 본인이 선택하면되고, 라이브러리를 사용하면 직접 Form이나 Input이나 버튼을 만들필요없이 가져다 사용하면됨.

코드를 작성 중이거나 작성 후 더 꼼꼼한 리뷰 과정이 필요하고, 구현이 안된 부분이나 변경할 부분들은 TODO로 남겨야함

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +    console.log(this.props);
불필요한 로그 삭제

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +  }
class 기반으로 props, state를 모두 사용한다면 constructor를 사용하면 좋을듯

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +  postAPI = async () => {
adapter폴더의 api.js 로 옮기고
명명을 `authorize`와 같은 로그인에 관련된 이름으로 해야함.

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +    if (this.validateEmail() === true && this.validatePassword() === true) {
Email과 Password가 서버에서 정한 규칙과 같게 설정하는 것이 좋을 것 같고
validation하는 외부 라이브러리들을 사용하는 것이 더 편할듯

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +            alert("User not found");
alert보다는 Input field의 아래에 에러 메세지가 출력되도록 하는 방식이 더 좋을듯

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +            alert("Wrong password");
alert보단 메세지 출력

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +            console.log(error.response.headers);
불필요한 로그 삭제
500이라면 input field 밑에 해당 에러에 대한 메세지를 띄워줘야함

에러 로깅은 console.error 등 에러 로깅을 위한 함수를 통해서 해야함

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +        <header className="Signin-header">
주로 id는 underscore, className은 hyphen을 사용해서 단어를 잇고 소문자를 사용함

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +const signInUrl = 'user/signin/'
[Constant Convention](https://google.github.io/styleguide/jsguide.html#naming-constant-names)에 따라 상수는 upperletter, underscore 조합으로 되어야함.

로컬 주소를 담은 base URL constant를 지정하고
axios.create으로 해당 base URL을 사용하는 axios client를 생성하는 api.js를 정의하고
각 http 요청마다 특정 path만을 넣어주는 방식이 효율적일듯

`user/signin`이 아닌 localhost 서버로 요청을 보내는 URI를 지정해야함

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +          console.log('Error', error.message);
에러 로깅은 console.error

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +  appChange = (e) => {
handleOnChange
함수는 동사형으로 명명

나머지 함수들도 변경 필요

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +  }
불필요하게 2번 감쌀 필요없이 밑의 if 안에서 호출하면 될 듯.

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +          <input type="email" id="inputEmail" className="form-control" placeholder="Enter e-mail" name="email" onChange={appChange} />
email input에서도 엔터를 입력해도 요청이 갈 수 있도록 해야함

2021-04-09 18:18 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +  }
email과 password validation에 유용한 외부 라이브러리를 찾아보고 적용하면 편할듯.
validation 조건은 서버에서 정한 규칙과 일관되어야 할 것 같음.

2021-04-11 05:45 UTC, psymoney commented on frontend/src/routes/Signin.js
> +            alert("User not found");
어떤점에서 더 좋은거임?

2021-04-11 06:03 UTC, psymoney commented on frontend/src/routes/Signin.js
> +  }
서버쪽 로그인 validation 조건은 없는데 이런 경우엔 어떻게 하는지?

2021-04-11 15:12 UTC, Jeldo requested changes
yarn으로 package management를 하는데 npm을 사용해서 package-lock.json이 생기고 있습니다. 
둘 중 하나만 사용해서 관리를 해야합니다.

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +  let response
semicolon 추가
https://google.github.io/styleguide/jsguide.html#disallowed-features-automatic-semicolon-insertion

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +          'Content-Type': 'application/json'
trailing comma 추가
https://google.github.io/styleguide/jsguide.html#features-objects-use-trailing-comma

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +          console.error(error.response.headers);
response는 오지만 위에서 정의한 403, 404가 아닌 경우 어떤 방식으로 유저에게 보여줄지 핸들링 해야합니다.

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +        console.error(error.request);
request가 가지 않는 경우일 것 같은데 이 경우엔 실제로 어떤 에러가 발생하는지 확인하고, 어떤 방식으로  핸들링 해야합니다.

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +        console.error('Error', error.message);
이 경우도 마찬가지

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +          console.error(error.response)
semicolon 추가
https://google.github.io/styleguide/jsguide.html#disallowed-features-automatic-semicolon-insertion

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/pages/Signin.js
> +          <input type="password" id="inputPassword" className="form-control" placeholder="Enter password" name="password" onChange={handleOnChange} onKeyPress={handleOnKeyPress}/>
80 column limit
https://google.github.io/styleguide/jsguide.html#formatting-column-limit

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +async function requestSignInAPI(email, password) {
signIn

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +          alert("User not found");
single quotes
https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +          alert("Wrong password");
single quotes
https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +      alert("Enter email");
single quotes
https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +      alert("enter password");
single quotes
https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +const SIGN_IN_URL = 'user/signin/'
semicolon 추가
https://google.github.io/styleguide/jsguide.html#disallowed-features-automatic-semicolon-insertion

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +      response = await axios.post(SIGN_IN_URL, { email: email, password: password }, {
80-column limit
https://google.github.io/styleguide/jsguide.html#formatting-column-limit

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +      alert("Given email does not follow email format")
single quotes
https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +    } else if(!validator.validate(email)) {
위 조건문에서 return이 될 경우 아래는 실행되지 않고 early return 되기 때문에 else if로 할 필요없이 아래도 if 로 하면됩니다.
```
if (A) {
  return false;
}
if (B) {
  return false;
}
return true;
```

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/pages/Signin.js
> +  }
80 column limit

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/pages/Signin.js
> +        <header className="Signin-header">
html/css 에서 className, id는 주로 소문자, 하이픈, 밑줄로 명명합니다.

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/setupProxy.js
> +};
Backend에서 cors setup을 프론트엔드 주소와 포트에 대해 허락하도록 설정하면 프록시가 필요없습니다.

2021-04-11 15:12 UTC, Jeldo commented on Backend/server/settings.py
> +    'corsheaders.middleware.CorsMiddleware',
middleware 추가만하고 별도로 cors 세팅이 되지 않았습니다.
https://github.com/adamchainz/django-cors-headers#configuration
참조해서 백엔드에서 CORS 환경설정을 해야합니다.

또한 이번 이슈는 프론트에 관한 이슈이므로 백엔드의 변경은 별도의 이슈로 관리를 해야합니다.

2021-04-11 15:12 UTC, Jeldo commented on frontend/package.json
> +  "proxy": "http://localhost:8000"
백엔드에서의 CORS 설정시 프록시 불필요

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +  if (validateEmail(email) === true && validatePassword(password) === true) {
API는 API에 관련된 부분만 다뤄야합니다. 필요한 인자들에 대한 유효성 검사는 authorize 함수에서 하고, 이 함수에서는 API 요청을 하고 응답에 대한 핸들링만 해야합니다.

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/pages/Signin.js
> +    let accessToken = await requestSignInAPI(this.state.email, this.state.password);
requestSignInAPI 내부의 validation 부분을 여기서 하고, 유효하다면 API 호출을 해야합니다.

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +      return null;
null 보다는 undefined를 사용합니다.

2021-04-11 15:12 UTC, Jeldo commented on frontend/src/adapter/SigninAPI.js
> +      if (error.response) {
if문이 중첩되는 경우 early return 방식으로 하는 것이 간결하게 보입니다.

2021-04-11 15:13 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +  }
서버쪽에서도 email format에 대해 같이 validation을 진행하면 될 것 같습니다.

2021-04-11 15:25 UTC, Jeldo commented on frontend/src/routes/Signin.js
> +            alert("User not found");
대부분의 웹사이트에서 로그인 실패시 alert보다는 텍스트 필드 밑에 에러 메세지를 띄우거나 작은 메세지 창을 옆으로 띄우도록 합니다. UX관점에서 볼 때 경고창을 띄우는 방법보다 좋다고 생각하는데, 마이너한 문제라고 생각된다면 alert을 사용해도 상관없습니다.

2021-04-11 15:33 UTC, Jeldo commented
Settings - Editor - Code Style - JavaScript ->
Wrapping and Braces: Hard wrap at 80
Punctuation: Use single quotes always
Trailing comma: Add when multiline

Settings - Plugins - Marketplace -> Save Actions 검색 후 설치
Settings - Save Actions -> General 1, 3 / Formatting Actions 1, 2, 4
기본적으로 세팅 후 본인이 필요한 기타 설정들 추가하면 저장시 대부분의 포맷 자동화 가능

2021-04-12 05:36 UTC, psymoney commented on frontend/src/routes/Signin.js
> +            alert("User not found");
그럼 각각 텍스트 필드 하단에도 메세지 띄울 영역을 할당하고 각 에러별로 적절한 메세지를 보내주는 식으로 구현하면 될거 같은데 이건 이슈에 반영하고 개선사항으로 적용해보겠음

2021-04-12 16:53 UTC, Jeldo requested changes
코멘트 수정 후 15d8677 커밋이랑 이번 수정 커밋 합쳐서 1개로 squash하고 force push하세요.
https://git-scm.com/book/ko/v2/Git-%EB%8F%84%EA%B5%AC-%ED%9E%88%EC%8A%A4%ED%86%A0%EB%A6%AC-%EB%8B%A8%EC%9E%A5%ED%95%98%EA%B8%B0

커밋 합치기 단락 참조

2021-04-12 16:53 UTC, Jeldo commented on frontend/package.json
> +    "http-proxy-middleware": "^0.19.1",
사용하지 않는 패키지 삭제

2021-04-12 16:53 UTC, Jeldo commented on frontend/src/adapter/signin.js
> +    }
response가 오지 않을경우에 대해서 핸들링이 되고 있지 않습니다. 서버에서 아예 응답이 오지 않는 network failure에 대한 고려가 필요합니다. 또한 이전 PR 코멘트에서 말했듯이 API에러에 대한 핸들링은 여기서하고, 유저에게 보여주는 UI단에서의 핸들링은 이 함수를 사용하는 해당 컴포넌트에서 처리를 해야합니다. 따라서 UI에 관여하고 있는 alert을 삭제하고 signin 컴포넌트에서 해야합니다.

https://github.com/axios/axios#handling-errors 참조

2021-04-12 16:53 UTC, Jeldo commented on frontend/src/pages/signin.js
> +  validateEmail = () => {
IsValidEmail

2021-04-12 16:53 UTC, Jeldo commented on frontend/src/pages/signin.js
> +  validatePassword = () => {
IsValidPassword

로그인시 비밀번호 오류는 보안 문제로 대개 자세한 에러 메세지를 나타내지 않고 '잘못된 패스워드입니다.' 정도의 메세지만 나타냅니다.

2021-04-12 16:53 UTC, Jeldo commented on frontend/src/pages/signin.js
> +    if (!this.validateEmail() === true && this.validatePassword() === true) {
조건문이 잘못되었습니다.
|   | T | F |
|---|---|---|
| T | O | X |
| F | X | X |

IsValidEmail이 참 그리고 IsValidPassword일 경우에만 조건문을 통과하고 나머지 경우에는 중단되어야 합니다.
또한 return type이 없는 access token만 받아와서 state로 설정하는 함수이므로 undefined를 리턴할 필요없이 return으로 함수를 중단하면 됩니다.

2021-04-12 16:53 UTC, Jeldo commented on frontend/src/pages/signin.js
> +    super();
인자로 props를 추가해야합니다.

2021-04-12 16:53 UTC, Jeldo commented on frontend/src/pages/signin.js
> +  handleOnKeyPress = (e) => {
불필요한 함수 삭제

2021-04-12 16:53 UTC, Jeldo commented on frontend/src/pages/signin.js
> +      return undefined;
`return;`
signIn에서 response가 오지 않았을 경우 UI에서 어떻게 처리할 지에 대한 핸들링이 필요합니다.

2021-04-12 16:53 UTC, Jeldo commented on frontend/src/pages/signin.js
> +                  id="submitButton">Sign-In</Button>
form tag안에 넣고, Button의 type을 `'submit'`으로 하면 form tag 내의 value들을 같이 제출할 수 있습니다.
```
<form onSubmit={~}>
  <input>A</input>
  <input>B</input>
  <button type="submit">C</button>
</form>
```
https://react-bootstrap.github.io/components/buttons/#button-tags

2021-04-12 16:53 UTC, Jeldo commented on frontend/src/adapter/signin.js
> +const SIGN_IN_URL = 'http://127.0.0.1:8000/user/signin/';
이후에 axios 호출을 더 하게 될텐데 BASE_URI를 별도로 지정하는 편이 더 낫습니다.
API가 변하지 않으면 path도 변하지 않으니 const 선언보다 axios 호출 부분에 남겨도 됩니다.

2021-04-13 01:13 UTC, psymoney commented on frontend/src/pages/signin.js
> +  handleOnKeyPress = (e) => {
ID와 password input 창에서 Enter키 입력시 API호출 함수 호출하는 함수인데 해당 함수 없이 onKeyPress 활용가능한지

2021-04-13 01:50 UTC, psymoney commented on frontend/src/pages/signin.js
> +                  id="submitButton">Sign-In</Button>
form tag랑 submit type button 같이 사용하는 경우 페이지 리로드 현상 발생해서 form 블럭 대신 div 사용함

2021-04-13 04:01 UTC, Jeldo commented on frontend/src/pages/signin.js
> +                  id="submitButton">Sign-In</Button>
https://stackoverflow.com/questions/50193227/basic-react-form-submit-refreshes-entire-page
https://developer.mozilla.org/ko/docs/Web/API/Event/preventDefault

2021-04-13 05:33 UTC, Jeldo requested changes

2021-04-13 05:33 UTC, Jeldo commented on frontend/src/adapter/signin.js
> +      return 'wrong password';
response가 오지 않을 경우 런타임 에러가 발생하게 됩니다.
https://github.com/axios/axios#handling-errors 에서 핸들링 과정이 설명되어있습니다.
```
if (error.response) // 응답은 오는데 2xx이 아닌 경우
else if (error.request) // 요청은 정상적으로 보내졌지만 응답이 오지 않는 경우. (Network Failure)
else // 요청이 제대로 만들어지지 않은 경우
```

`if (error.response)` 를 통해서 response가 있으면 status code에 따라 핸들링을 합니다.

2021-04-13 05:33 UTC, Jeldo commented on frontend/src/pages/signin.js
> +      <div className="signin-header">
https://stackoverflow.com/questions/50193227/basic-react-form-submit-refreshes-entire-page
https://developer.mozilla.org/ko/docs/Web/API/Event/preventDefault

authorize에서 event parameter를 받고, 해당 이벤트는 preventDefault를 호출해 새로고침을 방지하면됩니다.

2021-04-13 05:33 UTC, Jeldo commented on frontend/src/pages/signin.js
> +  authorize = async () => {
이 컴포넌트에서 onSubmit에 대한 핸들러는 하나 밖에 사용하지 않으므로 handleSubmit으로 명명해도 괜찮을 듯 합니다.

2021-04-13 05:33 UTC, Jeldo commented on frontend/src/pages/signin.js
> +    let data = await signIn(this.state.email, this.state.password);
data -> [token, err] 혹은 [response, err]

2021-04-13 05:33 UTC, Jeldo commented on frontend/src/pages/signin.js
> +               onChange={handleOnChange} onKeyPress={handleOnKeyPress}/>
handleOnKeyPress 삭제

2021-04-13 05:33 UTC, Jeldo commented on frontend/src/pages/signin.js
> +               onChange={handleOnChange} onKeyPress={handleOnKeyPress}/>
handleOnKeyPress 삭제

2021-04-13 05:33 UTC, Jeldo commented on frontend/src/adapter/signin.js
> +      return 'wrong password';
Design Doc에 정의한 status code 대해서는 message를 보냈었습니다. 해당 메세지를 활용하면 됩니다.

2021-04-13 05:33 UTC, Jeldo commented on frontend/src/pages/signin.js
> +  handleOnKeyPress = (e) => {
form tag 사용하면 핸들링 가능합니다

2021-04-13 05:33 UTC, Jeldo commented on frontend/src/adapter/signin.js
> +    return 'unexpeced error occurred. try it again.';
unexpected

2021-04-13 05:33 UTC, Jeldo commented on frontend/src/adapter/signin.js
> +      return 'user not found';
https://javascript.plainenglish.io/how-to-avoid-try-catch-statements-nesting-chaining-in-javascript-a79028b325c5
```
try{
  ...
} catch(err){
  return [undefined, 'message'];
}
return [returnValue, undefined];
```
  형태로 에러 메세지를 전달하고


받는 쪽에서는
```
let [token, err] = signIn(~);
if (err) {
  // handle error
}
// use token
```
위와 같은 방식으로 타입 체크 필요없이 값을 확인할 수 있습니다.

2021-04-13 15:17 UTC, psymoney commented on frontend/src/adapter/SigninAPI.js
> +      if (error.response) {
> if문이 중첩되는 경우 early return 방식으로 하는 것이 간결하게 보입니다.



> if문이 중첩되는 경우 early return 방식으로 하는 것이 간결하게 보입니다.

asd

2021-04-13 15:29 UTC, psymoney commented on frontend/src/adapter/signin.js
> +      return 'wrong password';
https://github.com/psymoney/stocker/pull/59/commits/43dc84cd632686ed5639a0d25ac0b0967aa676b1#r611202450
early return으로 구현하라고 해서,
아래 `if (error.request)` 에서 request는 호출되고 response 없는 경우 핸들링,
if문이 잡지못했으나 발생한 에러를 `console.error(error)`가 처리하는 형태로 구현했는데

서버쪽에서 반환하는 status 종류가 200, 400(no email 또는 no password), 403(wrong pw), 404(user not found) 네 가지인데 그럼 400에 대한 핸들링만 추가하면 되는지?

2021-04-13 15:46 UTC, Jeldo requested changes

2021-04-13 15:46 UTC, Jeldo commented on frontend/src/adapter/signin.js
> +  return [response.data.accessToken, undefined];
```
catch (err) {
  if (err.response) {
    if(err.response.statue == 4xx) {
      return [undefined, 'message']
    }
    ..
    // handle other defined status codes
    ..
  }
  if (err.request) {
    ..
    return [undefined, 'message'];
  }
  return [undefined, 'message'];
}
```

2021-04-13 16:20 UTC, Jeldo approved these changes

2021-04-13 16:20 UTC, Jeldo commented on frontend/src/adapter/signin.js
> +      }
만약 프론트엔드에서 response는 오는 경우, 어차피 response에서 받아오는 message를 그대로 출력하기 때문에 status code에 따라 다른 액션을 할 것이 아니라면 굳이 이렇게 분기할 필요도 없습니다. 
이 경우엔 non-2xx response body에 언제나 message가 있어야 합니다.
```
if (error.response) {
  return [undefined, error.response.data.message];
}
```
본인이 선택하고 squash하고 머지하세요

2021-04-13 16:28 UTC, merged